<a href="/beer/create">New Beer</a>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Style</th>
      <th>Img</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($this->beers as $beer): ?>
      <tr>
        <th scope="row"><?php echo $beer['id'];?></th>
        <td><?php echo $beer['name'];?></td>
        <td><?php echo $beer['style'];?></td>
        <td><img src="<?php echo $beer['img'];?>"></td>
        <td><a href="/beer/edit/<?php echo $beer['id'];?>">Edit</a></td>
        <td><a href="/beer/delete/<?php echo $beer['id'];?>">Delete</a></td>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>