<?php echo $this->form()->openTag($form); ?>
<div class="form_element">
    <?php echo $this->formRow($form->get('name')); ?>
</div>

<div class="form_element">
    <?php echo $this->formRow($form->get('style')); ?>
</div>

<div class="form_element">
    <?php echo $this->formRow($form->get('img')); ?>
</div>

<?php if ($form->has('id')): ?>
    <?php echo $this->formElement($form->get('id')) ?>
<?php endif;?>

<?php echo $this->formElement($form->get('send')) ?>

<?php echo $this->form()->closeTag() ?>